## Spring Jackson
#spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
#spring.jackson.time-zone=GMT+8
#
## MySQL
#spring.datasource.dynamic.primary=mhmain
#spring.datasource.dynamic.datasource.mhmain.url=jdbc:mysql://nj-cdb-hq9uquar.sql.tencentcdb.com:63971/mhmain?characterEncoding=utf-8&serverTimezone=GMT%2B8
#spring.datasource.dynamic.datasource.mhmain.username=root
#spring.datasource.dynamic.datasource.mhmain.password=gzsxdfsadfdss#@123
#spring.datasource.dynamic.datasource.mhmain.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.datasource.dynamic.datasource.mhsch_1.url=jdbc:mysql://nj-cdb-hq9uquar.sql.tencentcdb.com:63971/mhsch_1?characterEncoding=utf-8&serverTimezone=GMT%2B8
#spring.datasource.dynamic.datasource.mhsch_1.username=root
#spring.datasource.dynamic.datasource.mhsch_1.password=gzsxdfsadfdss#@123
#spring.datasource.dynamic.datasource.mhsch_1.driver-class-name=com.mysql.cj.jdbc.Driver
#
## Redis
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#spring.data.redis.database=0
#spring.data.redis.timeout=60s
#spring.data.redis.lettuce.pool.max-active=10
#spring.data.redis.lettuce.pool.max-idle=8
#spring.data.redis.lettuce.pool.min-idle=0
#spring.data.redis.lettuce.pool.max-wait=5s
#
## Servlet
#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.max-file-size=1000MB
#spring.servlet.multipart.max-request-size=1000MB
#
## Sa-Token
#sa-token.token-name=satoken
#sa-token.timeout=2592000
#sa-token.active-timeout=-1
#sa-token.is-concurrent=false
#sa-token.is-share=false
#sa-token.token-style=uuid
#sa-token.is-log=true
#
## Server
#server.port=2867
#
## COS
#cos.secretId=
#cos.secretKey=
#cos.regionName=ap-nanjing
#cos.bucketName=guozejiaoyu-1317857445
#
##52428800?? =  50MB, 104857600?? = 100MB
#upload.chunkSize=52428800
#
## ??????jar??? ????
## java -jar guoze-spring-1.0.0.jar --spring.config.additional-location=file:D:\Desktop\jar\application.properties